import {stores} from "../core/stores/Stores";
export function f(str: any, ...values: any[]): string {
    // str.raw = `Поделиться ${10} визиткой`;
    return stores.localizationStore.Languages[stores.localizationStore.currentLang][str[0]] || str[0];//locales_ru[str[0]] || str[0];
}

export function pluralise(count: number, one: string, few: string, more: string): string {
    if (count > 10 && count < 21) {
        return more;
    }

    const _10 = count % 10;
    if (_10 === 1) {
        return one;
    }

    if (_10 > 5 || _10 === 0) {
        return more;
    }

    return few;
}

export const locales_ru_default: { [key: string]: string } = {
    "Share my contact": "Поделиться визиткой",
    "I'am in the Era System": "Я в системе ERA",
    "My Profile": "Мой профиль",
    "Invalid address": "Не корректный адрес",
    "Person not found": "Персона не найдена",
    "Need select image": "Необходимо выбрать изображение",
    "error_1": "Поле ФИО должно содержать не менее 12 символов",
    "error_2": "Необходимо заполнить поле описание",
    "error_3": "Необходимо выбрать дату рождения",
    "error_4": "Необходимо указать место рождения",
    "error_5": "Введите корректный адрес персоны",
    "error_6": "Все поля обязательны для заполнения",
    "error_7": "Актив не выбран",
    "error_8": "Не удалось получить информацию о персоне",
    "error_9": "Ошибка разбора данных.",
    "Header": "Заголовок",
    "confirmed person": "удостоверенная персона",
    "anonimous person": "Анонимный пользователь",
    "unconfirmed person": "не удостоверенная персона",
    "connection lost": "Соединение потеряно",
    "receiving profile": "Получение пользователя",
    "uncomfirmed": "не подтверждено",
    "confirmations": "подтверждений",
    "License Text": "Текст лицензии",
    "person confirmation": "Удостоверение персоны",
    "Confirm": "Подтвердить",
    "Insert address person": "Вставьте адрес персоны",
    "Please, insert secret key": "Пожалуйста, вставьте секретный ключ",
    "I Accept": "Я принимаю",
    "Account": "Счет",
    "account number": "номер счета:",
    "secret key generated": "Сгенерирован секретный ключ.\nСкопируйте его в буфер и сохраните в безопасном, надежном месте",
    "Insert form buffer": "Вставьте персону из буфера",
    "Accounts": "Счета",
    "press icon right": "Для вставки нажмите иконку справа",
    "Sent": "Отправить",
    "Restore old": "Восстановить старый",
    "Create new": "Создать новый",
    "Person data": "Данные персоны",
    "Persons dict": "Справочник персон",
    "Assets dict": "Справочник активов",
    "Sorry not found": "Извините, по вашему запросу ничего не найдено.",
    "Settings": "Настройки",
    "input pin": "Введите пин-код",
    "Person profile": "Профиль персоны",
    "Favorite persons": "Избранные персоны",
    "Find person in era": "Найти Персону в Erachain",
    "Searching, wait": "Подождите, выполняется поиск…",
    "message_1": "Транзакция не принята сервером.\nВаш баланс не изменится.",
    "message_1.1": "Транзакция не принята сервером.",
    "message_2": "Транзакция принята сервером.\nВаш баланс изменится после\n ее подтверждения.",
    "message_2.1": "Транзакция принята сервером.",
    "message_3": "Избранные активы отсутствуют, выберите активы из Erachain",
    "message_4": "Вставьте секретный ключ в следующее поле",
    "message_5": "ERA wallet не обнаружил наустройстве секретный ключ",
    "message_6": "Избранные персоны отсутствуют выберите персоны из Erachain",
    "message_7": "Избранные персоны не найдены выполните поиск в Erachain",
    "Create Wallet": "Создать кошелёк",
    "Find in Fav": "Найти в избранных",
    "Amount": "Количество",
    "Decline": "Отказаться",
    "Verify": "Удостоверить",
    "Active Name": "Наименование актива",
    "Comment": "Комментарий",
    "Send Active": "Отправить актив",
    "Copied from clipboard": "Скопировано из буфера обмена",
    "Copied to clipboard": "Скопировано в буфер обмена",
    "Copy to clipboard": "Копировать в буфер",
    "no records": "Записи отсутствуют",
    "no fav assets": "Список избранных Активов пуст",
    "AddToFavorite": "Добавить в избранные",
    "Add Asset To Favorite": "Добавить в избранное",
    "RemoveFromFavorite": "Удалить из избранных",
    "Remove Asset From Favorite": "Удалить из избранного",
    "Recipient": "Получатель",
    "Keys": "Ключи",
    "Private Key": "Публичный ключ",
    "Public bank key": "Публичный ключ для банка",
    "Private key": "Секретный ключ",
    "Server": "Сервер",
    "Add Server": "Добавить сервер",
    "not enoght COMPU": "Не достаточно COMPU",
    "confirm pls": "Подтвердите выполнение транзакции перевода",
    "Yours address": "Ваш адрес",
    "Yours contacts": "Ваши контакты",
    "Send active": "Отправить Актив",
    "My wallet": "Мой кошелек",
    "Copy account": "Копировать счёт",
    "Yours correct address": "Ваш Erachain адрес:",
    "Copy open key": "Копировать открытый ключ",
    "Transactions history": "История транзакций",
    "Register Person": "Регистрация персоны",
    "Transaction": "Транзакция",
    "User address": "Адрес пользователя",
    "Send transfer": "Отправить перевод",
    "Message": "Сообщение",
    "Size": "Размер",
    "will be fee": "Будет удержан сбор",
    "Add": "Внести",
    "Info": "Сведения",
    "Search": "Поиск",
    "Import": "Импорт",
    "Additional form": "Дополнительная форма",
    "birthplace": "место рождения",
    "Full name": "ФИО",
    "description": "описание",
    "birth date": "дата рождения",
    "Continue": "Продолжить",
    "License": "Лицензия",
    "Blue": "Синий",
    "Green": "Зелёный",
    "Brown": "Карий",
    "lightBlue": "Голубой",
    "I'm in Era: ": "Я в ERA: ",
    "Favorite assets": "Избранные активы",
    "Find in Era": "Поиск актива в Erachain",
    "g": "г.",
    "Gray": "Серый",
    "Blond": "Блондин",
    "Olive": "Оливковый",
    "Yantar": "Янтарный",
    "Brunette": "Брюнет",
    "Brown-haired": "Шатен",
    "Red-haired": "Рыжий",
    "oldGray": "Седой",
    "Rusiy": "Русый",
    "Male": "Мужской",
    "Female": "Женский",
    "Yelow": "Жёлтый",
    "Afro": "Чёрный",
    "Search persons in Erachain": "Поиск Персон в Erachain",
    "Favorite is empty": "Список избранного пуст",
    "eye color": "цвет глаз",
    "hair color": "цвет волос",
    "sex": "пол",
    "Height": "Рост",
    "Remove from contacts list": "Удалить из контактов",
    "Select place": "Выберите место",
    "Next": "Далее",
    "Favorite Persons": "Избранные Персоны",
    "Favorite Actives": "Избранные Активы",
    "Share data": "Поделиться данными",
    "Favorite": "Избранное",
    "Preson is not Confirmed": "Персона не удостоверена",
    "Transaction Confirmation": "Подтверждение транзакции",
    "Close": "Закрыть",
    "Declare": "Удостоверение",
    "Select from gallery": "Выбрать фото из галереи",
    "Make new photo": "Сделать новое фото",
    "Remove photo": "Удалить фото",
    "WorkWithPersons": "Работа с персонами",
    "User data": "Данные пользователя",
    "create pin": "Создайте пин-код",
    "confirm pin": "Повторите пин-код",
    "pins do not match": "Пин-коды не совпадают",
    "Back": "Назад",
    "Add photo": "Добавить фото",
    "Register": "Регистрация",
    "Wallet": "Кошелек",
    "Language": "Язык"
};
export const locales_en_default: { [key: string]: string } = {
    "Share my contact": "Share",
    "I'am in the Era System": "I'm in ERA",
    "My Profile": "My Profile",
    "Invalid address": "Invalid address",
    "Person not found": "Person not found",
    "Need select image": "You have to select image",
    "error_1": "The field name must contain at least 12 characters",
    "error_2": "Field description required",
    "error_3": "You must select a date of birth",
    "error_4": "Place of birth is required",
    "error_5": "Enter the correct address of the person",
    "error_6": "All fields are required",
    "error_7": "Asset is not selected",
    "error_8": "Could not retrieve information about the person",
    "error_9": "Error parsing data.",
    "Header": "Header",
    "confirmed person": "confirmed person",
    "anonimous person": "Anonymous user",
    "unconfirmed person": "unconfirmed person",
    "connection lost": "Connection lost",
    "receiving profile": "Receiving person",
    "uncomfirmed": "not confirmed",
    "confirmations": "confirmations",
    "License Text": "License text",
    "person confirmation": "Person's confirmation",
    "Confirm": "Confirm",
    "Insert address person": "Paste person's address",
    "Please, insert secret key": "Please, paste secret key",
    "I Accept": "I Accept",
    "Account": "Account",
    "account number": "account number:",
    "secret key generated": "Secret key has generated.\nCopy it to clipboard and save in the safe place.",
    "Insert form buffer": "Insert person from the Clipboard",
    "Accounts": "Accounts",
    "press icon right": "Press icon right to insert",
    "Sent": "Send",
    "Restore old": "Restore old",
    "Create new": "Create new",
    "Person data": "Person's data",
    "Persons dict": "Persons directory",
    "Assets dict": "Assets directory",
    "Sorry not found": "Sorry, there is nothing found by your request",
    "Settings": "Settings",
    "input pin": "input pin",
    "Person profile": "Person profile",
    "Favorite persons": "Favorite persons",
    "Find person in era": "Find person in Erachain",
    "Searching, wait": "Wait, searching…",
    "message_1": "The transaction was not accepted by the server.\nВаш баланс не изменится.",
    "message_1.1": "The transaction was not accepted by the server.",
    "message_2": "The transaction was accepted by the server.\nYour balance will change after\n confirmation.",
    "message_2.1": "The transaction was accepted by the server.",
    "message_3": "Favorite assets not found. Search assets in Erachain",
    "message_4": "Insert secret key to the next field",
    "message_5": "ERA wallet did not found secret key on your device",
    "message_6": "Favorite persons not found. Search in Erachain",
    "message_7": "Favorite persons not found. Search in Erachain",
    "Create Wallet": "Create Wallet",
    "Find in Fav": "Find in favorites",
    "Amount": "Amount",
    "Decline": "Decline",
    "Verify": "Verify",
    "Active Name": "Asset's name",
    "Comment": "v",
    "Send Active": "Send asset",
    "Copied from clipboard": "Copied from clipboard",
    "Copied to clipboard": "Copied to clipboard",
    "Copy to clipboard": "Copy to clipboard",
    "no records": "There is no records",
    "no fav assets": "Favorite assets list is empty",
    "AddToFavorite": "Add to favorites",
    "Add Asset To Favorite": "Add to favorite",
    "RemoveFromFavorite": "Remove from favorites",
    "Remove Asset From Favorite": "Remove from favorite",
    "Recipient": "Recipient",
    "Keys": "Keys",
    "Private Key": "Public key",
    "Public bank key": "Public key for the bank",
    "Private key": "Private key",
    "Server": "Server",
    "Add Server": "Add Server",
    "not enoght COMPU": "Not enough COMPU",
    "confirm pls": "Confirm transaction",
    "Yours address": "Your address",
    "Yours contacts": "Your contacts",
    "Send active": "Send Asset",
    "My wallet": "My wallet",
    "Copy account": "Copy account",
    "Yours correct address": "Your Erachain address:",
    "Copy open key": "Copy open key",
    "Transactions history": "Transactions history",
    "Register Person": "Register Person",
    "Transaction": "Transaction",
    "User address": "User address",
    "Send transfer": "Send transfer",
    "Message": "Message",
    "Size": "Size",
    "will be fee": "fee will be withheld",
    "Add": "Add",
    "Info": "Info",
    "Search": "Search",
    "Import": "Import",
    "Additional form": "Additional form",
    "birthplace": "birthplace",
    "Full name": "Full name",
    "description": "description",
    "birth date": "birth date",
    "Continue": "Continue",
    "License": "License",
    "Blue": "Blue",
    "Green": "Green",
    "Brown": "Brown",
    "lightBlue": "Light blue",
    "I'm in Era: ": "I'm in ERA: ",
    "Favorite assets": "Favorite assets",
    "Find in Era": "Find Assets in Erachain",
    "g": "",
    "Gray": "Gray",
    "Blond": "Blond",
    "Olive": "Olive",
    "Yantar": "Amber",
    "Brunette": "Brunette",
    "Brown-haired": "Brown-haired",
    "Red-haired": "Ginger",
    "oldGray": "Gray-haired",
    "Rusiy": "Blond",
    "Male": "Male",
    "Female": "Female",
    "Yelow": "Yellow",
    "Afro": "Black",
    "Search persons in Erachain": "Search persons in Erachain",
    "Favorite is empty": "Favorite list is empty",
    "eye color": "eye color",
    "hair color": "hair color",
    "sex": "sex",
    "Height": "Height",
    "Remove from contacts list": "Remove from contacts list",
    "Select place": "Select place",
    "Next": "Next",
    "Favorite Persons": "Favorite Persons",
    "Favorite Actives": "Favorite Assets",
    "Share data": "Share data",
    "Favorite": "Favorite",
    "Preson is not Confirmed": "Person does not confirmed",
    "Transaction Confirmation": "Transaction Confirmation",
    "Close": "Close",
    "Declare": "Declare",
    "Select from gallery": "Select from gallery",
    "Make new photo": "Take a new picture",
    "Remove photo": "Remove photo",
    "WorkWithPersons": "Deal with persons",
    "User data": "User data",
    "create pin": "Create pin",
    "confirm pin": "Confirm pin",
    "pins do not match": "Pins do not match",
    "Back": "Back",
    "Add photo": "Add photo",
    "Register": "Register",
    "Wallet": "Wallet",
    "Language": "Language"
};
